INCFLAGS := -I$(CORE_DIR)/libretro-common/include

SOURCES_C := $(CORE_DIR)/libretro.c \
    $(wildcard $(CORE_DIR)/crocods-core/*.c) \
    $(wildcard $(CORE_DIR)/crocods-core/iniparser/*.c) \
    $(wildcard $(CORE_DIR)/deps/libz/*.c) \
    $(CORE_DIR)/libretro-common/compat/compat_posix_string.c \
    $(CORE_DIR)/libretro-common/compat/compat_strcasestr.c \
    $(CORE_DIR)/libretro-common/compat/compat_strl.c \
    $(CORE_DIR)/libretro-common/compat/fopen_utf8.c \
    $(CORE_DIR)/libretro-common/encodings/encoding_utf.c \
    $(CORE_DIR)/libretro-common/file/file_path.c \
    $(CORE_DIR)/libretro-common/file/file_path_io.c \
    $(CORE_DIR)/libretro-common/file/retro_dirent.c \
    $(CORE_DIR)/libretro-common/streams/file_stream.c \
    $(CORE_DIR)/libretro-common/string/stdstring.c \
    $(CORE_DIR)/libretro-common/time/rtime.c \
    $(CORE_DIR)/libretro-common/vfs/vfs_implementation.c
