SOURCES_C := $(CORE_DIR)/libretro.c \
    $(wildcard $(CORE_DIR)/crocods/*.c) \
    $(wildcard $(CORE_DIR)/crocods/resources/*.c) \
    $(wildcard $(CORE_DIR)/zip/*.cpp) \
    $(wildcard $(CORE_DIR)/zip/zlib/*.c)
