SOURCES_C := $(CORE_DIR)/libretro.c \
    $(wildcard $(CORE_DIR)/crocods-core/*.c) \
    $(wildcard $(CORE_DIR)/crocods-core/resources/*.c) \
    $(wildcard $(CORE_DIR)/deps/*.c) \
    $(wildcard $(CORE_DIR)/deps/libz/*.c)
